(() => {
const CARD_DEFINITIONS = {
  zacian: {
    id: "zacian",
    name: "ザシアン",
    type: "unit",
    hp: 3,
    power: 0,
    effectKey: "attackPowerPlusFive",
    text: "攻撃時、パワーを+5する。",
  },
  calyrexShadow: {
    id: "calyrexShadow",
    name: "黒バド",
    type: "unit",
    hp: 1,
    power: 4,
    effectKey: "drawTwoOnDeath",
    text: "やられた時、2ドロー。",
  },
  zapdos: {
    id: "zapdos",
    name: "サンダー",
    type: "unit",
    hp: 2,
    power: 3,
    effectKey: "attackOrGainLife",
    text: "攻撃するか、ライフ+2を選ぶ。7以上も可能。",
  },
  tyranitar: {
    id: "tyranitar",
    name: "バンギ",
    type: "unit",
    hp: 4,
    power: 2,
    effectKey: "damageAllOthersAfterAct",
    text: "行動後、生きていれば自分以外の全モンスターに1ダメージ。",
  },
  rillaboom: {
    id: "rillaboom",
    name: "ゴリラ",
    type: "unit",
    hp: 3,
    power: 2,
    effectKey: "useTargetPowerAsDamage",
    text: "モンスター攻撃時、相手のパワーをダメージにする。",
  },
  quagsire: {
    id: "quagsire",
    name: "ヌオー",
    type: "unit",
    hp: 3,
    power: 1,
    effectKey: "ignorePowerIncreases",
    text: "能力によるパワー上昇を無効化。",
  },
  snorlax: {
    id: "snorlax",
    name: "カビゴン",
    type: "unit",
    hp: 5,
    power: 1,
    effectKey: "blockLifeAttacks",
    text: "場にいる間、ライフ攻撃させない。",
  },
  pikachu: {
    id: "pikachu",
    name: "ピカチュウ",
    type: "unit",
    hp: 1,
    power: 1,
    effectKey: "none",
    text: "効果なし。",
  },
  focusSash: {
    id: "focusSash",
    name: "気合いのタスキ",
    type: "item",
    effectKey: "surviveLethalAtOne",
    text: "一度だけ攻撃を耐える。",
  },
  choiceBand: {
    id: "choiceBand",
    name: "拘り鉢巻",
    type: "item",
    effectKey: "attackPowerPlusTwo",
    text: "パワーを+2する。",
  },
  assaultVest: {
    id: "assaultVest",
    name: "突撃チョッキ",
    type: "item",
    effectKey: "maxHpPlusTwo",
    text: "HPを+2する。",
  },
  destinyCloak: {
    id: "destinyCloak",
    name: "道連れマント",
    type: "item",
    effectKey: "destroyOpponentOnDeath",
    text: "モンスターが倒れた時、相手も破壊する。",
  },
  lightBall: {
    id: "lightBall",
    name: "でんきだま",
    type: "item",
    effectKey: "pikachuPowerPlusFive",
    text: "ピカチュウが持つとパワー+5。",
  },
  robbery: {
    id: "robbery",
    name: "強奪",
    type: "action",
    effectKey: "stealOpponentItems",
    text: "相手のモンスターの持ち物をすべて自分の手札に加える。",
  },
  endingBell: {
    id: "endingBell",
    name: "終わりの鐘",
    type: "action",
    effectKey: "setAllCurrentHpToOne",
    text: "このターン、全モンスターの現在HPを1にする。",
  },
  erase: {
    id: "erase",
    name: "消し去る",
    type: "action",
    effectKey: "discardUnit",
    text: "モンスター1体を捨札に送る。",
  },
  circulation: {
    id: "circulation",
    name: "循環",
    type: "action",
    effectKey: "drawThreeDiscardTwo",
    text: "1山から3枚ドローして2枚捨てる。",
  },
  courtChange: {
    id: "courtChange",
    name: "コートチェンジ",
    type: "action",
    effectKey: "swapUnits",
    text: "自分と相手の場のモンスターを入れ替える。",
  },
  storm: {
    id: "storm",
    name: "嵐",
    type: "action",
    effectKey: "drawOneEachDiscardOne",
    text: "各山から1枚ずつドローし、好きなカードを1枚捨てる。",
  },
  reviveCrystal: {
    id: "reviveCrystal",
    name: "元気の塊",
    type: "action",
    effectKey: "reviveUnit",
    text: "捨札からモンスターを1体選び場に出す。",
  },
  laboratory: {
    id: "laboratory",
    name: "研究室",
    type: "action",
    effectKey: "drawTwoGainAction",
    text: "1山から2枚ドローする。",
  },
  quickTechnique: {
    id: "quickTechnique",
    name: "早業",
    type: "action",
    effectKey: "doubleNextAction",
    text: "このターン、次のアクションカードを2回処理する。",
  },
  excavation: {
    id: "excavation",
    name: "発掘",
    type: "action",
    effectKey: "takeDiscardToHand",
    text: "捨札からカード1枚を選び手札に加える。",
  },
  doubleCheck: {
    id: "doubleCheck",
    name: "二重チェック",
    type: "action",
    effectKey: "discardOpponentHand",
    text: "相手の手札を見て1枚捨札に送る。",
  },
  stoneThrow: {
    id: "stoneThrow",
    name: "石投げ",
    type: "action",
    effectKey: "dealTwoToUnitOrLife",
    text: "モンスター1体、または相手ライフに2ダメージ。",
  },
};

const CARD_POOL = [
  "zacian",
  "calyrexShadow",
  "zapdos",
  "tyranitar",
  "rillaboom",
  "quagsire",
  "snorlax",
  "pikachu",
  "focusSash",
  "choiceBand",
  "assaultVest",
  "destinyCloak",
  "lightBall",
  "robbery",
  "endingBell",
  "erase",
  "circulation",
  "courtChange",
  "storm",
  "reviveCrystal",
  "laboratory",
  "quickTechnique",
  "excavation",
  "doubleCheck",
  "stoneThrow",
];

const PILE_DEFINITIONS = [
  { id: "pileA", name: "山札A" },
  { id: "pileB", name: "山札B" },
  { id: "pileC", name: "山札C" },
];

const cardGameCards = {
  CARD_DEFINITIONS,
  CARD_POOL,
  PILE_DEFINITIONS,
};
if (typeof window !== "undefined") window.CardGameCards = cardGameCards;
if (typeof module !== "undefined") module.exports = cardGameCards;
})();
